### ISSUE TITLE
Front page design

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#163]
The current front page is visually attractive, but it is easy to miss that the portal itself provides direct access to data. The header tabs (drillcores, samples etc) are much less prominent than the colorful cards that take user to external pages.
The problem could be solved by:

- Adding a most prominent search box and slogan to the header banner, or 
- Adding individual colorful cards in the first row (drillcores, samples, etc), or
- Adding a 12 unit wide card that is for the e-Maapõu portal, with search box in the middle. Then the header bar should be redesigned on the front page to avoid duplication.

**Comment by enmust** [comment]
Only front page should use prominent header
