### ISSUE TITLE
read LAS files

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#202]
Geophysical data files are often in LAS format - example https://geocollections.info/attachment/156720
Numeric data from these could be easily read info an array and then displayed for a section (almost exclusively drill cores).
Full file format specification: 
ver 2 https://www.cwls.org/wp-content/uploads/2014/09/LAS_20_Update_Jan2014.pdf
ver 3 https://www.cwls.org/wp-content/uploads/2014/09/LAS_3_File_Structure.pdf

Essentially we need to read the parameter names, which are listed below line starting with "~CURVE" (skipping comment lines). The first column is depth information. Number of other parameters is not limited (in example file "Natural Gamma").
And then read the data below line starting with "~A"
Delimiters could be: (multiple) spaces, tabs, or commas.
There may be thousands or tens of thousands of rows in a file.

These data can be shown along section profile (in FLOG, or Plotly - like in Eurocore - a separate issue will be created for graphs).

File example:
![image](https://user-images.githubusercontent.com/14974887/111041355-77589700-8440-11eb-8c08-cafc3376ac3f.png)

**Comment by Erikdzo** [comment]
There are several packages available that can parse LAS files.

Python:
* lasio (works with LAS 2.0, 3.0 support is being added)
* las-converter (works with LAS 2.0)

JS:
* las-js (works with LAS 2.0)

**Comment by enmust** [comment]
Probably file contents should be read in API side

**Comment by enmust** [comment]
How data is drawn / shown is still open for discussion (separate app / package or sth else)

**Comment by enmust** [comment]
Related to #https://github.com/geocollections/public-geoloogia-api/issues/7

**Comment by enmust** [comment]
.las file content as json: https://api.geoloogia.info/file/156720/?raw_content=true
.las file content as text: https://api.geoloogia.info/file/156720/

same applies to .txt files
.txt file content as json: https://api.geoloogia.info/file/1530/?raw_content=true
.txt file content as text: https://api.geoloogia.info/file/1530/

**Comment by enmust** [comment]
Closing as api now return readable data + first grapg versions already used in geoloogia app
