### ISSUE TITLE
Stratigraphy links to stratigraphy detail view

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#258]

**Comment by ollehints** [comment]
- Stratigraphy detail view should use simple header
- Stratotypes map should zoom out 7 times compared to the current view, it should show Estonian map and activate Estonian bedrock overlay. If multiple stratotypes, all should be visible 
- Map should zoom out also on other pages
- Links to other stratigraphic units should be internals links (in general info, in subunits, in lithostratigraphy)
- Links to stratotype locality should be opened within the app
