### ISSUE TITLE
Drillcore with wrong boxes

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#262]
Drillcore with no boxes shows all box images of all cores:
https://dev.geoloogia.info/drillcore/1/
![image](https://user-images.githubusercontent.com/14974887/113816784-f611cd00-977d-11eb-8bc2-7ac14380c4c7.png)

**Comment by Erikdzo** [comment]
The main problem is that the route is not changed according to what tabs are available. When entering drillcore/1 no drillcore boxes are found and therefore the next tab should be shown and the route changed (in this case to drillcore/1/references).

Right now there is no way to access the tab that drillcore boxes tab is replaces by (in this case references). This is probably a issue in every detail view.
