### ISSUE TITLE
Edit button

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#294]
Currently not shown

**Comment by Erikdzo** [comment]
The query to https://rwapi.geocollections.info/is_logged_in/login_state from sarvTwapi.api.js file seems to always return false when queried.
![image](https://user-images.githubusercontent.com/24605643/114348371-1b804b80-9b6f-11eb-9faa-3af362cc6365.png)

If the query is opened in a separate tab the query returns true.
![image](https://user-images.githubusercontent.com/24605643/114348429-2d61ee80-9b6f-11eb-8e59-de8e9a9426c5.png)

**Comment by enmust** [comment]
Yup, it's the separate domain issue. We could make the edit button always shown.

**Comment by enmust** [comment]
OK for now
