### ISSUE TITLE
missing app header in detail view

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/eMaapou#302]
When you open a detail view from any of the search views while the app header is not prominent. The app header will disappear from the detail view.

To reproduce:
1. open any of the search views
2. scroll down far enough, so that the app header is no longer prominent
3. click a link to open the detail view

**Comment by Erikdzo** [comment]
This bug will probably be fixed by updating the header to be the same everywhere.

**Comment by enmust** [comment]
header updatred
