### ISSUE TITLE
images not loading

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#312]
@Erikdzo it seems to be related to latest update [components/templates/Detail.vue](https://github.com/geocollections/eMaapou/blob/f14b408ede4fea7cd1276619f34bef5c2da1b657/components/templates/Detail.vue)

**Comment by ollehints** [comment]
it shows up for few seconds on language change

**Comment by ollehints** [comment]
some page still have problems:
https://dev.geoloogia.info/en/drillcore_box/3598/

**Comment by enmust** [comment]
Should be ok now
