### ISSUE TITLE
update site index

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#323]
add eng fields (project_name_en)

**Comment by enmust** [comment]
index updated

**Comment by Erikdzo** [comment]
Searching using project_name_en in Solr does not work.

https://api.geocollections.info/solr/site/?q=*&fq=(project_name_en%253A(*Grain*%2520AND%2520*size*%2520AND%2520*distribution*%2520AND%2520*of*%2520AND%2520*sand*%2520AND%2520*and*%2520AND%2520*gravel*))+AND+(latitude:[*+TO+*]+OR+(*:*+AND+-latitude:[*+TO+*]))+AND+(longitude:[*+TO+*]+OR+(*:*+AND+-longitude:[*+TO+*]))&start=0&rows=25&sort=id_l+desc

**Comment by enmust** [comment]
seems to work now, wanted reindexing
