### ISSUE TITLE
Site view updates

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#335]
Site table view (https://dev.geoloogia.info/site) should show latitude and longitude fields instead of X and Y, as these are present in more records. Add also area field after site name.
In site detail view integrate data from the "Location" table into General info, so that the map can be large, like in case of locality.
Add locality_description and attachments subforms (like in locality view, but linked via site_id and attachment_link__site_id).
We could also show site_images as "image bar" like in case of outcrops (image files, connected via attachment_link__site_id).

**Comment by Erikdzo** [comment]
> Add locality_description and attachments subforms (like in locality view, but linked via site_id and attachment_link__site_id).

This is already added, if I am not mistaken. Examples sites: 5777 and 5631. Or have I misunderstood something?
