### ISSUE TITLE
Investigate map zoom levels

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#344]
Should be possible to zoom closer

**Comment by Erikdzo** [comment]
In which route did this happen? I have not managed to recreate the problem.

**Comment by enmust** [comment]
Current max zoom is 30m but the problem was that if layers has the options you should be able to zoom in even closer

**Comment by enmust** [comment]
Maybe try this could help: https://leafletjs.com/reference-1.7.1.html#gridlayer-maxnativezoom
