### ISSUE TITLE
Map tiles resolution

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#354]
Map tiles sometimes come in high-resolution mode, which makes all labels very small:
https://dev.geoloogia.info/locality/10218/
![image](https://user-images.githubusercontent.com/14974887/115679721-8abe2280-a35b-11eb-8575-8779681f1028.png)

In older version, and sometimes in newer, larger labels are shown:
https://geoloogia.info/locality/10218/
![image](https://user-images.githubusercontent.com/14974887/115680158-fd2f0280-a35b-11eb-8414-4a9580b9e7a3.png)

**Comment by enmust** [comment]
Could try this:

![image](https://user-images.githubusercontent.com/14908993/115695167-35d5d880-a36a-11eb-885b-7be392c0f981.png)

**Comment by enmust** [comment]
Closing this as it seems to be ok
