### ISSUE TITLE
Search specimen/sample number with acronym

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#355]
Specimen and sample numbers in publication are often preceded with institutional acronym. Thus quick search by "GIT 160-7" should get results including specimen 4939. Currently a search by two string gets no results if one of the strings contains "-" within one string: https://dev.geoloogia.info/search/?q=GIT%20160-7

**Comment by enmust** [comment]
Tested and seems to work as expected thus can be closed
