### ISSUE TITLE
Add project to analytical data search options

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#375]
We need the possibility to search analytical data by project, but currently project is only linked to site. We need direct link between sample and project. Dataset is usually smaller than project. Sample series is also usually smaller than project (or equal to it).
For instance, ResTA is a multi-institutional project that has common samples, and shared analytical data from several sections (boreholes), analysed in different institutions etc. A user would like to limit analytical data to all results of a project.

**Comment by enmust** [comment]
db relation added

**Comment by enmust** [comment]
index also updated
