### ISSUE TITLE
Analytical data issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#379]
Analytical data results table should start with ID column and data to be sorted by default by id DESC.
Andmekogu=Andmeset, it should show dataset_id instead of name
depth_interval field could be omitted to save space
default parameters could be those with more data - hence Ag, Au not the best. Maybe use CaO, MgO, SiO, Al2O3
Filter fields should start with locality/locality_en and depth (as range) 
In filters, andmekogu=andmeset
Filter by analysis_id should also be possible.

**Comment by ollehints** [comment]
In future, a user should be able to select which fields to show in the table (for instance, sometimes user would like to see both depth and depth_interval fields for exporting data). Displaying method and method details would also be desirable quite often.

**Comment by enmust** [comment]
make param not clearable (null check)

**Comment by enmust** [comment]
parameter sorting (sort missing last)

**Comment by enmust** [comment]
site to locality
