### ISSUE TITLE
Leaflet map error when switching detail search

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/eMaapou#393]
![image](https://user-images.githubusercontent.com/24605643/116875263-48ca9180-ac23-11eb-992a-fdd4ab152bee.png)

For some reason, when switching from locality search view to any other route, leaflet throws a error. This does not seem to happen in any other search view.

It does not seem to break anything noticeable.

**Comment by enmust** [comment]
Added wontfix because it doesn't seem to break or change anything. If we have time or it do breaks sth then maybe we can work on it.

**Comment by enmust** [comment]
Cause is still unknown and it doesn't seem to break anything, closing this becuase of that
