### ISSUE TITLE
Align dataset with DOI

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#414]
Dataset module should be better aligned with DOI module so that it would be more straightforward to create DOI from analytical dataset. This concerns matching fields in tables and adding new fields to dataset. Database and API config should be updated.
Also, add direct links to primary reference (new field reference_id) and locality (new field locality_id) for those datasets that concern single section (then the defined datasets can be shown as subforms in locality and drillcore views).

**Comment by ollehints** [comment]
Then SARV-WB also needs updating

**Comment by enmust** [comment]
Done
