### ISSUE TITLE
Query drillcores by map

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#463]
The map should have controls to draw basic shapes and make solr query using coordinates. This would work like in fossiilid.info advanced search. Drillcore index now has solr spatial field and can be queried by user drawn bbox like this:

https://api.geocollections.info/solr/drillcore/?fq=%7B%21field%20f--latlong%7DisWithin(POLYGON((22.071656%2058.676938,23.213504%2058.676938,23.213504%2059.130863,22.071656%2059.130863,22.071656%2058.676938)))&fq=%7B%21collapse%20field--locality%7Drows=1&format=json

**Comment by ollehints** [comment]
NB! for some reason crosshair cursor disappeared from the map. But it is better not to select individual sites and localities by clicking but allow to select data of particular module - for instance, in sample view, map should enable the user to search for samples rather than link to localities.

**Comment by enmust** [comment]
Todos:

- [ ] clear button should remove layers from map
- [ ] investigate polygon search (coordinates wrong etc, review fossiilid code, probably needs some reversing)

**Comment by enmust** [comment]
Note: Solr is using JTS for spatial search which supports only **clockwise** orientation for the outer ring. 
More info: https://gis.stackexchange.com/questions/119150/order-of-polygon-vertices-in-general-gis-clockwise-or-counterclockwise
