### ISSUE TITLE
Making URLs more readable and SEO friendly

### ISSUE THREAD

**Issue by enmust** [geocollections/eMaapou#595]
Example:

Current version https://geoloogia.info/locality/23832/
New version https://geoloogia.info/locality/23832/valingu-mois-harjumaa

Similar solutions can be seen in delfi.ee, postimees.ee or err.ee

Our case seems more difficult as we also have subroutes
Current version: https://geoloogia.info/locality/23846/aegna-saar/specimens
New version: https://geoloogia.info/locality/23846/aegna-saar/specimens

Probably needs some research etc.

**Comment by enmust** [comment]
Added wontfix label for now maybe in the future

**Comment by Erikdzo** [comment]
Currently slugs have not been added to files, news, preparations

**Comment by enmust** [comment]
Closing as slugs now added
