### ISSUE TITLE
wrong las files shown?

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#624]
Seemingly wrong .las files are shown - in case of https://dev.geoloogia.info/drillcore/500/toolse-ph011b-puursudamik/attachments there are no attached files, but a graph is shown.

**Comment by enmust** [comment]
.las file is coming from related locality.

Related attachments need to be updated (have to add or_search to the query). 
At first when we changed the api url, new api didnt't have the or_search functionality

**Comment by enmust** [comment]
Closed it as or_search was now added
