### ISSUE TITLE
rock link in specimen view heading

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#707]
Formal rock names in specimen view heading take user to undefined instead of correct rock in kivid.info. For instance "settekivimid" in heading in https://geoloogia.info/specimen/79910/rock-identifications link to https://kivid.info/undefined

**Comment by Erikdzo** [comment]
Fixed in https://github.com/geocollections/eMaapou/commit/4244dfe9ddaee36cdfc644435bc7cc2cecb18641
