### ISSUE TITLE
Search by specimen number containing ":"

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#738]
It should be possible to quickly search for specimens by number containing ":" - this is part of number in Estonian Museum of Natural History. For instance, specimen 200959 (https://geoloogia.info/specimen/200959) should be found when searching for "G440:627", but ":" breaks the search.

**Comment by enmust** [comment]
In order to escape ":" backslash needs to be added. Probably should leave quick search as it is because then we would remove the functionality to search on certain fields. (depends which use case is more important) In detail search we should escape it.

**Comment by Erikdzo** [comment]
Specimen number field now escapes all Solr special characters. #841
