### ISSUE TITLE
Specimen detail page issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#739]
Specimen detail view should link to collection view. Currently does not work. In future we should create simple collection view. 
Old number field should be shown after specimen number.
Sample number with link to sample view should be shown after agent_collected field.
Example: https://geoloogia.info/specimen/4898 should show "Sc 52" and "OM-2" and link to https://geocollections.info/collection/107

**Comment by Erikdzo** [comment]
Collection link needs to be added

**Comment by Erikdzo** [comment]
Discard the last comment. It has been added already.
