### ISSUE TITLE
Area detail view issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#747]
Area detail view should show data from tables maaamet_maeeraldis and maaamet_maardla, if maeeraldis_id or maardla_id are present in the area table (models and config needs to be updated for new fields in area table and for the two new tables).
It should be clearly indicated that data from maaamet_... tables comes from Maa-amet / Estonian Land Board. 
Perhaps we should build index to include the related fields from maardla and maeeraldis in order to search for e.g. mining companies?
Once we have postgis tables, then spatial object should be shown on map.

"Up icon" takes user to site list view, instead of area list view.
![image](https://user-images.githubusercontent.com/14974887/150674611-d0fa87bc-6d2f-4881-97c5-dd88f589660e.png)

**Comment by ollehints** [comment]
index now includes data on mineral deposit, resource etc

**Comment by ollehints** [comment]
Area view should have two additional but mutually exclusive tables: deposits and mining claims.

If deposit_id>0 then show maaamet_maardla table below the General info table:
Table heading: Deposit / Maardla
Now text: "These data are from Estonian Land Board database" / "Järgnevad andmed on pärit Maa-ameti maardlate nimistust".
Now table with following labels and fields:

- Deposit ID / Maardla ID: maardla_id
- Registration No. / Registrikaardi Nr: reg_kaart
- Name / Nimi: nimetus (maardla_os)
- Area (ha) / Pindala (ha): pindala
- Bedrock / Aluspõhi: aluspohja -> boolean checkbox
- Commodity / Maavara: maavara
- Usage / Kasutuskohad: pohimaavar
- Additional commodity / Kaasnevad maavarad: 
- Mining conditions / Mäenduslikud tingimused: maeteh_ti
- Environmental restrictions / Keskkonnakaitselised piirangud: geookol_ti
- Data export date / Andmed eksporditud: eksporditi

**reg_kaart** field should link to (and open in new window):
https://xgis.maaamet.ee/xgis2/page/app/maardlad?showsearchlayer=1&searchid=FUU7966&REGISTRIKAART=$reg_kaart &hide=true


If maeeraldis_id>0 then show maaamet_maeeraldis table below the General info table:
Table heading: Mining claim/ Mäeeraldis
Now text: "These data are from Estonian Land Board database" / "Järgnevad andmed on pärit Maa-ameti maardlate nimistust".
Now table with following labels and fields:

- Claim ID / Mäeeraldise ID: me_id
- Claim No. / Mäeeraldise Nr: me_kood
- Deposit registration No. / Maardla registrikaardi Nr: reg_kaart
- Name / Nimi: nimetus (maardla_os)
- Area / Pindala: pindala
- Reserve / Varu: erald_varu
- Usage / Kasutuse eesmärk: kas_eesm
- Reclamation / Taastamine: rekult
- Status / Olek: me_olek
- Extraction permit No. / Kaevandusloa Nr: loa_number (loa_algus - loa_lopp)
- Permit owner / Loa omanik: loa_omanik
- Mining company / Kaevandaja: kaevandaja
- Data export date / Andmed eksporditud: eksporditi

**loa_number** field should link to (and open in new window):
https://xgis.maaamet.ee/xgis2/page/app/maardlad?showsearchlayer=1&searchid=FUU7935&LOA_NUMBER=$loa_number&hide=true

**Comment by ollehints** [comment]
Show area on the map if polygon field is filled with geojson coordinates. Sample areas: 1542 and 2379
But, in geojson coordinates come as lon,lat, but leaflet expects lat,lon
Use code from sarv-doi app which can show areas from doi_geolocation table.

**Comment by ollehints** [comment]
now API calls to new tables possible, and area contains links to maardla and maeeraldis:

- https://api.geoloogia.info/maaamet_maardla/
- https://api.geoloogia.info/maaamet_maeeraldis/

**Comment by ollehints** [comment]
Show parent_area in the main table, just below area_type. This would come from nested data from parent_area object, show name/name_en, and link internally to parent_area via parent_area_id. Labels: Belongs to: / Kuulub:

Add child areas into subform (similar to sites belonging to area) - for instance, for a deposit, all mining claims would be shown (like Orgita deposit would contain several claims: https://geoloogia.info/area/1415). Heading: Realted areas / Seotud alad.

Additionally, we need to add localities that are related to an area are show them like sites. Heading: Related localities / Seotud lokaliteedid. Example: Orgita deposit https://geoloogia.info/area/1415 would contain at least one locality: https://geoloogia.info/locality/13491 NB! API needs to be updated.

**Comment by Erikdzo** [comment]
The related area table needs to be updated to use fields from API. Currently it uses fields from Solr and therefore fields like type and county cannot be shown.

**Comment by Erikdzo** [comment]
Need to add area_type and country type text value fields to Solr area and locality index.
