### ISSUE TITLE
Specimen filter issues

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#837]
Issues with specimen detailed search:

- search by specimen number searches from specimen_full_name field, https://api.geoloogia.info/solr/specimen?q=%2A&fq=%28%28specimen_full_name%3A%2ASc%20101%2A%29%29&start=0&rows=25 and returns all records 
  - this index field should be renamed to specimen_number_full
  - specimen number filter should used fields specimen_number, specimen_number_old, specimen_number_full
- search field "fossil" is not fossil name, but group, label should be renamed to "fossil group" / "fossiilirühm"
- filter by fossil name is needed (from fields taxon, taxon_txt, taxon_full)
- index field hierarchy_string should be renamed to taxon_hierarchy
  - how to search this field hierarchically - similarly to stratigraphy filter
- filter by related reference is needed - autocomplete like for stratigraphy
- filter by rock name using rock, rock_en, rock_txt, rock_txt_en, formula

**Comment by ollehints** [comment]
the filters should also include:
- map view / filter (like in samples)
- has_image
- has_map

**Comment by enmust** [comment]
added map search, there were some issues solr indexing example:
![image](https://user-images.githubusercontent.com/14908993/176704305-33a57f75-3997-405d-811b-f3076bc2260c.png)

**Comment by enmust** [comment]
> - search by specimen number searches from specimen_full_name field, https://api.geoloogia.info/solr/specimen?q=%2A&fq=%28%28specimen_full_name%3A%2ASc%20101%2A%29%29&start=0&rows=25 and returns all records 
>   - this index field should be renamed to specimen_number_full
>   - specimen number filter should used fields specimen_number, specimen_number_old, specimen_number_full
> - ~~search field "fossil" is not fossil name, but group, label should be renamed to "fossil group" / "fossiilirühm"~~
> - filter by fossil name is needed (from fields taxon, taxon_txt, taxon_full)
> - index field hierarchy_string should be renamed to taxon_hierarchy
>   - how to search this field hierarchically - similarly to stratigraphy filter
> - filter by related reference is needed - autocomplete like for stratigraphy
> - filter by rock name using rock, rock_en, rock_txt, rock_txt_en, formula

**Comment by enmust** [comment]
filters updated, I believe reference filter is not working correctly as it is returning too many results. Probably needs some extra work.

**Comment by ollehints** [comment]
Reference filter needs to have quotes:
https://api.geoloogia.info/solr/specimen?q=*&fq=((specimen_references:%22N%C3%B5lvak%20et%20al.,%202022%22))&start=0&rows=25
