### ISSUE TITLE
dataset data view

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#877]
Dataset view should have separate tabs for analyses and numeric results, and optionally charts (if samples have depths and come from a single locality). 
* analyses table should show (where possible translated):
  * analysis_id (link to analysis view)
  * sample_number (link to sample view)
  * locality / site
  * stratigraphy
  * analysis_method
  * lab
* results table (grouped by samples, coming from e.g. https://api.geoloogia.info/solr/sample_data?fq=dataset_id%3A105&q=%2A&start=0&rows=25):
  * sample_number (link to sample view)
  * locality / site
  * latitude (hidden by default)
  * longitude (hidden by default)
  * stratigraphy
  * then all parameters measured within the dataset (like Al2O3_pct, Fe2O3_pct, dolomite_pct etc)

**Comment by ollehints** [comment]
This view will become very important for presenting and accessing all types of analytical data

**Comment by Erikdzo** [comment]
Do i understand correctly that, the analysis table should not show parameters measured?

Also, should locality and site be shown in separate columns? As there are cases where both are defined.
