### ISSUE TITLE
Map filter returns wrong localities

### ISSUE THREAD

**Issue by Erikdzo** [geocollections/eMaapou#909]
Found a case, where setting a rectangular search area on the map returned localities that were outside of the area.

Not sure what might be the cause. Could it be that Solr spatial search takes into account the curvature of Earth?

Ex. https://geoloogia.info/locality?page=1&itemsPerPage=25&sortBy=id&sortDesc=true&geoJSON=%7B%22type%22%3A%22Feature%22,%22properties%22%3A%7B%7D,%22geometry%22%3A%7B%22type%22%3A%22Polygon%22,%22coordinates%22%3A%5B%5B%5B11.953125,46.581518%5D,%5B11.953125,56.286059%5D,%5B32.871094,56.286059%5D,%5B32.871094,46.581518%5D,%5B11.953125,46.581518%5D%5D%5D%7D%7D

**Comment by ollehints** [comment]
yes, this is related to latlong query by cartesian rectangle, especially evident with latitudinally extended search:
https://dev.geoloogia.info/locality?page=1&itemsPerPage=500&sortBy=id&sortDesc=true&map=%7B%22type%22%3A%22Feature%22,%22properties%22%3A%7B%7D,%22geometry%22%3A%7B%22type%22%3A%22Polygon%22,%22coordinates%22%3A%5B%5B%5B21.851694,58.631217%5D,%5B21.851694,58.699776%5D,%5B27.648992,58.699776%5D,%5B27.648992,58.631217%5D,%5B21.851694,58.631217%5D%5D%5D%7D%7D

so nothing wrong
