### ISSUE TITLE
Integrate drillcore with FLOG2

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#93]
Can we integrate FLOG2 (http://geokogud.info/flog2/examples/default/) into drillcore and locality views, to be shown on separate tab "Section" / "Läbilõige"?
The main idea is to allow users to output svg file with stratigraphy and samples in suitable scale (to adjust in other programs like Illustrator or Inkscape).

**Comment by enmust** [comment]
Currently using other solutions
