### ISSUE TITLE
Specimen views

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#937]
In list view:
- [x] hide ID by default
- [x] make name the second column
- [x] hide depth_interval by default
- [x] hide lithostratigraphy by default

Filters:
- [x] order: specimen_number, collection number, taxon_hierarchy, taxon_name, rock_name, locality, country, map, stratigraphy, depth, literature, collector, original_status
- [x] collection number should come from autocomplete like in old portal
- [x] reference filter has typo and not look for reference field - better to use author field anyway

**Comment by Erikdzo** [comment]
Currently missing the `rock_name` filter. This should be based on rock hierarchy, right? @ollehints
