### ISSUE TITLE
wrong images and relations

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#955]
seemingly random images appear in specimen view:
![image](https://user-images.githubusercontent.com/14974887/216638261-ef9343dd-6e53-4042-b97b-9d5d0c363ad6.png)

in sample view, preview image is not shown:
![image](https://user-images.githubusercontent.com/14974887/216638682-e0845eb0-1bd5-41d1-859e-56a96ab196f1.png)

in drillcore view, wrong samples are shown:
![image](https://user-images.githubusercontent.com/14974887/216639257-01137a31-3a90-424d-b919-dfacbccb97da.png)

probably additional similar issues

**Comment by Erikdzo** [comment]
this is fixed
