### ISSUE TITLE
locality taxon list

### ISSUE THREAD

**Issue by ollehints** [geocollections/eMaapou#964]
Locality view should include list of taxa from the taxon_search index as a separate tab, before specimens. Search parameters:
fq=locality_id:$locality_id (example fq=locality_id:12431)
fq=rank:[14 TO 18]
sort=taxon ASC

Tab title Fossil genera and species / Leitud fossiilid

**Comment by Erikdzo** [comment]
What columns should this table contain?

**Comment by ollehints** [comment]
columns and default sorting:
fossil group, sorted ASC
name, sorted ASC
parent
src_txt / src_txt_en : "Esinemine põhineb" / "Occurrence based on" 

let's remove LAD and FAD as this may create confusion bc they are global values but user may see then as related to the particulat locality
